### ISSUE TITLE
Wyze, Inc.

### ISSUE THREAD

**Issue by IIAIronWolf** [Wyzetalk/wyzetalk-react-test#16]
You may want to change your company name before you get into legal trouble with Wyze, Inc. Especially if this company plans on doing business in the United States. This is just a friendly warning.

**Comment by IIAIronWolf** [comment]
www.wyze.com

**Comment by RemeJuan** [comment]
The company name is Wyzetalk, not Wyze. What logical reason would exists for us to change a name that is not the snake, nor similar nor works in the same industry???
